Repository impierce/ssi-agent, pull requests merged in 2024-08, with the labels that each got.

#98 refactor: implement `IssuanceServices` for signing and verifying
  Cargo.lock
  Cargo.toml
  agent_api_rest/src/issuance/credential_issuer/credential.rs
  agent_api_rest/src/issuance/credential_issuer/token.rs
  agent_api_rest/src/issuance/credential_issuer/well_known/oauth_authorization_server.rs
  agent_api_rest/src/issuance/credential_issuer/well_known/openid_credential_issuer.rs
  agent_api_rest/src/issuance/credentials.rs
  agent_api_rest/src/issuance/offers.rs
  agent_api_rest/src/lib.rs
  agent_api_rest/src/verification/authorization_requests.rs
  agent_api_rest/src/verification/relying_party/redirect.rs
  agent_api_rest/src/verification/relying_party/request.rs
  agent_application/docker/docker-compose.yml
  agent_application/example.config.yaml
  agent_application/src/main.rs
  agent_issuance/src/credential/aggregate.rs
  agent_issuance/src/credential/mod.rs
  agent_issuance/src/credential/services.rs
  agent_issuance/src/lib.rs
  agent_issuance/src/offer/aggregate.rs
  agent_issuance/src/offer/mod.rs
  agent_issuance/src/offer/services.rs
  agent_issuance/src/server_config/aggregate.rs
  agent_issuance/src/server_config/mod.rs
  agent_issuance/src/server_config/services.rs
  agent_issuance/src/services.rs
  agent_secret_manager/Cargo.toml
  agent_secret_manager/src/aggregate.rs
  agent_secret_manager/src/commands.rs
  agent_secret_manager/src/events.rs
  agent_secret_manager/src/lib.rs
  agent_secret_manager/src/services.rs
  agent_secret_manager/src/subject.rs
  agent_shared/Cargo.toml
  agent_shared/src/config.rs
  agent_shared/src/domain_linkage/mod.rs
  agent_shared/src/lib.rs
  agent_shared/tests/test-config.yaml
  agent_store/src/in_memory.rs
  agent_store/src/postgres.rs
Labels: Enhancement

#104 fix: change `url` to `uri`
  CHANGELOG.md
  agent_api_rest/src/issuance/credential_issuer/well_known/openid_credential_issuer.rs
  agent_application/example.config.yaml
  agent_shared/src/config.rs
  agent_shared/tests/test-config.yaml
  agent_verification/src/services.rs
Labels: Bug

#101 fix: implement `ES256` verification
  Cargo.lock
  agent_issuance/src/credential/aggregate.rs
  agent_secret_manager/Cargo.toml
  agent_secret_manager/src/subject.rs
  agent_secret_manager/tests/res/all_slots.stronghold
  agent_shared/src/config.rs
  agent_shared/src/domain_linkage/mod.rs
  agent_verification/src/authorization_request/aggregate.rs
Labels: Bug

#106 refactor: update local Docker setup
  agent_application/docker/.env.example
  agent_application/docker/README.md
  agent_application/docker/compose.yaml
  agent_application/docker/db/pgadmin4/servers.json
Labels: Documentation, Enhancement

#107 docs: application configuration
  agent_application/CONFIGURATION.md
Labels: Documentation

#108 ci: allow manual Docker builds
  .github/workflows/build-push-docker.yaml
Labels: Chore

#105 perf: cache DID documents (optional)
  .env.example
  .github/workflows/build-push-docker.yaml
  Cargo.lock
  Cargo.toml
  agent_api_rest/src/verification/relying_party/redirect.rs
  agent_application/CONFIGURATION.md
  agent_application/Cargo.toml
  agent_application/example.config.yaml
  agent_application/src/main.rs
  agent_issuance/Cargo.toml
  agent_issuance/src/services.rs
  agent_secret_manager/src/lib.rs
  agent_secret_manager/src/subject.rs
  agent_shared/Cargo.toml
  agent_shared/src/config.rs
  agent_verification/src/authorization_request/aggregate.rs
  agent_verification/src/connection/aggregate.rs
  agent_verification/src/services.rs
Labels: Enhancement
