Repository impierce/ssi-agent, pull requests merged in 2024-12, with the labels that each got.

#135 feat: return collections as arrays, generic primary identifiers
  agent_api_rest/postman/ssi-agent.postman_collection.json
  agent_api_rest/src/holder/holder/credentials/mod.rs
  agent_api_rest/src/holder/holder/offers/accept.rs
  agent_api_rest/src/holder/holder/offers/mod.rs
  agent_api_rest/src/holder/holder/offers/reject.rs
  agent_api_rest/src/holder/holder/presentations/mod.rs
  agent_api_rest/src/holder/openid4vci/mod.rs
  agent_api_rest/src/identity/connections/mod.rs
  agent_api_rest/src/identity/services/mod.rs
  agent_api_rest/src/issuance/credential_issuer/credential.rs
  agent_api_rest/src/issuance/credentials.rs
  agent_api_rest/src/issuance/offers/mod.rs
  agent_api_rest/src/verification/authorization_requests.rs
  agent_holder/src/credential/aggregate.rs
  agent_holder/src/credential/command.rs
  agent_holder/src/credential/event.rs
  agent_holder/src/credential/queries/mod.rs
  agent_holder/src/offer/aggregate.rs
  agent_holder/src/offer/command.rs
  agent_holder/src/offer/event.rs
  agent_holder/src/offer/queries/all_offers.rs
  agent_holder/src/offer/queries/mod.rs
  agent_holder/src/presentation/aggregate.rs
  agent_identity/src/connection/aggregate.rs
  agent_identity/src/document/aggregate.rs
  agent_identity/src/service/aggregate.rs
  agent_identity/src/service/views/mod.rs
  agent_issuance/src/credential/aggregate.rs
  agent_issuance/src/credential/command.rs
  agent_issuance/src/credential/event.rs
  agent_issuance/src/credential/views/mod.rs
  agent_issuance/src/offer/aggregate.rs
  agent_issuance/src/offer/views/mod.rs
Labels: Breaking change

#149 fix: persist Linked Verifiable Presentations for `did:web`
  agent_identity/src/service/aggregate.rs
  agent_identity/src/service/event.rs
  agent_identity/src/service/views/mod.rs
  agent_identity/src/state.rs
Labels: Bug

#152 feat: implement liveness probe at `/healthz`
  agent_api_rest/postman/ssi-agent.postman_collection.json
  agent_application/src/main.rs
  agent_application/src/probes/liveness.rs
  agent_application/src/probes/mod.rs
Labels: Added

#157 fix: change `/request` endpoint Content-Type to `oauth-authz-req+jwt`
  Cargo.lock
  Cargo.toml
  agent_api_rest/src/verification/relying_party/request.rs
  agent_verification/src/authorization_request/aggregate.rs
Labels: Breaking change

#141 feat: upload holder credentials via HTTP API
  agent_api_rest/postman/ssi-agent.postman_collection.json
  agent_api_rest/src/holder/holder/credentials/mod.rs
  agent_api_rest/src/holder/holder/offers/accept.rs
  agent_api_rest/src/holder/mod.rs
  agent_holder/src/credential/aggregate.rs
  agent_holder/src/credential/command.rs
  agent_holder/src/credential/event.rs
  agent_holder/src/credential/queries/mod.rs
Labels: Added

#150 feat: require credential expiration date, use credential `id` in JWT
  Cargo.lock
  Cargo.toml
  agent_api_rest/postman/ssi-agent.postman_collection.json
  agent_api_rest/src/issuance/credential_issuer/credential.rs
  agent_api_rest/src/issuance/credentials.rs
  agent_application/docker/db/init.sql
  agent_holder/src/offer/aggregate.rs
  agent_holder/src/presentation/aggregate.rs
  agent_issuance/Cargo.toml
  agent_issuance/README.md
  agent_issuance/src/credential/aggregate.rs
  agent_issuance/src/credential/command.rs
  agent_issuance/src/credential/error.rs
  agent_shared/Cargo.toml
  agent_verification/Cargo.toml
  agent_verification/src/authorization_request/aggregate.rs
Labels: Added, BREAKING CHANGE, Enhancement
