Repository impierce/ssi-agent, pull requests merged in 2024-11, with the labels that each got.

#143 style: box `CredentialConfigurationsSupportedObject`
  agent_api_rest/src/issuance/credentials.rs
  agent_issuance/src/credential/aggregate.rs
  agent_issuance/src/credential/command.rs
  agent_issuance/src/credential/event.rs
  agent_issuance/src/credential/queries/mod.rs
Labels: Chore

#97 ci: introduce semantic versioning
  .github/workflows/lint-pr-title.yaml
  .github/workflows/release.yaml
  .releaserc.yaml
  README.md
  commitlint.config.mjs
Labels: Added

#131 feat: bootstrap `Connection` aggregate
  Cargo.lock
  Cargo.toml
  agent_api_rest/Cargo.toml
  agent_api_rest/postman/ssi-agent.postman_collection.json
  agent_api_rest/src/identity/connections/mod.rs
  agent_api_rest/src/identity/mod.rs
  agent_api_rest/src/verification/relying_party/redirect.rs
  agent_application/docker/db/init.sql
  agent_event_publisher_http/Cargo.toml
  agent_event_publisher_http/README.md
  agent_event_publisher_http/src/lib.rs
  agent_identity/Cargo.toml
  agent_identity/src/connection/README.md
  agent_identity/src/connection/aggregate.rs
  agent_identity/src/connection/command.rs
  agent_identity/src/connection/error.rs
  agent_identity/src/connection/event.rs
  agent_identity/src/connection/mod.rs
  agent_identity/src/connection/views/all_connections.rs
  agent_identity/src/connection/views/mod.rs
  agent_identity/src/lib.rs
  agent_identity/src/state.rs
  agent_shared/src/config.rs
  agent_store/src/in_memory.rs
  agent_store/src/lib.rs
  agent_store/src/postgres.rs
  agent_verification/src/authorization_request/README.md
  agent_verification/src/authorization_request/aggregate.rs
  agent_verification/src/authorization_request/command.rs
  agent_verification/src/authorization_request/error.rs
  agent_verification/src/authorization_request/event.rs
  agent_verification/src/authorization_request/views/mod.rs
  agent_verification/src/connection/aggregate.rs
  agent_verification/src/connection/command.rs
  agent_verification/src/connection/error.rs
  agent_verification/src/connection/queries.rs
  agent_verification/src/lib.rs
  agent_verification/src/state.rs
Labels: Added, Breaking change

#146 ci: disable automated pre-releases, refer to release notes on GitHub
  .github/workflows/release.yaml
  CHANGELOG.md
Labels: Documentation, Enhancement
