Repository impierce/ssi-agent, pull requests merged in 2024-06, with the labels that each got.

#60 fix: add `state` to `AuthorizationResponseVerified` events
  agent_verification/src/connection/aggregate.rs
  agent_verification/src/connection/event.rs
  agent_verification/src/connection/queries.rs
Labels: Bug

#63 fix: add image `tags` in `merge` job
  .github/workflows/build-push-docker.yaml
Labels: Bug

#66 feat: enable `CorsLayer` (permissive) based on env variable
  .env.example
  Cargo.toml
  agent_api_rest/README.md
  agent_application/src/main.rs
Labels: Enhancement

#69 feat: add `offer_id` to all `OfferEvent` events
  agent_api_rest/src/issuance/credential_issuer/credential.rs
  agent_api_rest/src/issuance/credential_issuer/token.rs
  agent_api_rest/src/issuance/credentials.rs
  agent_api_rest/src/issuance/offers.rs
  agent_event_publisher_http/src/lib.rs
  agent_issuance/src/offer/aggregate.rs
  agent_issuance/src/offer/command.rs
  agent_issuance/src/offer/event.rs
  agent_issuance/src/offer/queries/mod.rs
Labels: Enhancement

#74 ci: use dedicated `arm64` runner
  .github/workflows/build-push-docker.yaml
Labels: Enhancement

#76 ci: automate build and publish when push to `dev`
  .github/workflows/build-push-docker.yaml
Labels: Enhancement

#72 feat: add support for `PresentationDefinition` by value
  agent_api_rest/postman/ssi-agent.postman_collection.json
  agent_api_rest/src/verification/authorization_requests.rs
  agent_api_rest/src/verification/relying_party/redirect.rs
  agent_api_rest/src/verification/relying_party/request.rs
Labels: Added

#31 feat: produce and serve `did:web` DID documents
  .env.example
  Cargo.lock
  Cargo.toml
  agent_api_rest/postman/ssi-agent.postman_collection.json
  agent_application/Cargo.toml
  agent_application/src/main.rs
  agent_secret_manager/Cargo.toml
  agent_secret_manager/src/aggregate.rs
  agent_secret_manager/src/subject.rs
Labels: Added

#78 docs: list available events
  agent_event_publisher_http/README.md
Labels: Documentation

#77 feat: create and serve `Domain Linkage Credential`
  .env.example
  Cargo.lock
  Cargo.toml
  agent_api_rest/postman/ssi-agent.postman_collection.json
  agent_application/Cargo.toml
  agent_application/src/main.rs
  agent_secret_manager/Cargo.toml
  agent_secret_manager/src/subject.rs
  agent_shared/Cargo.toml
  agent_shared/src/domain_linkage/mod.rs
  agent_shared/src/domain_linkage/verifiable_credential_jwt.rs
  agent_shared/src/error.rs
  agent_shared/src/lib.rs
Labels: Added

#79 chore: use `domain-linkage` (no `-fetch`) feature in `identity_credential`
  .github/pull_request_template.md
  Cargo.lock
  Cargo.toml
  agent_shared/Cargo.toml
  agent_verification/Cargo.toml
Labels: Bug

#80 chore: add tracing to `agent_event_publisher_http`
  Cargo.lock
  agent_event_publisher_http/Cargo.toml
  agent_event_publisher_http/src/lib.rs
Labels: Enhancement

#82 feat: add Metadata `config.yml` file
  .env.example
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  agent_api_rest/Cargo.toml
  agent_api_rest/src/issuance/credential_issuer/credential.rs
  agent_api_rest/src/issuance/credential_issuer/token.rs
  agent_api_rest/src/issuance/credential_issuer/well_known/oauth_authorization_server.rs
  agent_api_rest/src/issuance/credential_issuer/well_known/openid_credential_issuer.rs
  agent_api_rest/src/issuance/credentials.rs
  agent_api_rest/src/issuance/offers.rs
  agent_api_rest/src/lib.rs
  agent_api_rest/src/verification/authorization_requests.rs
  agent_api_rest/src/verification/relying_party/redirect.rs
  agent_api_rest/src/verification/relying_party/request.rs
  agent_application/Cargo.toml
  agent_application/config.yml
  agent_application/docker/README.md
  agent_application/docker/docker-compose.yml
  agent_application/src/main.rs
  agent_issuance/Cargo.toml
  agent_issuance/src/credential/aggregate.rs
  agent_issuance/src/offer/aggregate.rs
  agent_issuance/src/startup_commands.rs
  agent_secret_manager/Cargo.toml
  agent_secret_manager/src/lib.rs
  agent_secret_manager/src/services.rs
  agent_secret_manager/src/subject.rs
  agent_shared/Cargo.toml
  agent_shared/src/config.rs
  agent_shared/src/lib.rs
  agent_shared/src/metadata.rs
  agent_shared/tests/config.rs
  agent_store/src/postgres.rs
  agent_verification/Cargo.toml
  agent_verification/src/authorization_request/aggregate.rs
  agent_verification/src/connection/aggregate.rs
  agent_verification/src/services.rs
Labels: Breaking change

#83 feat: add `/v1/configurations/credential_configurations` endpoint
  .env.example
  CHANGELOG.md
  agent_api_rest/postman/ssi-agent.postman_collection.json
  agent_api_rest/src/configurations/credential_configurations.rs
  agent_api_rest/src/configurations/mod.rs
  agent_api_rest/src/issuance/credential_issuer/well_known/openid_credential_issuer.rs
  agent_api_rest/src/lib.rs
  agent_application/docker/README.md
  agent_event_publisher_http/README.md
  agent_issuance/src/server_config/aggregate.rs
  agent_issuance/src/server_config/command.rs
  agent_issuance/src/server_config/event.rs
  agent_issuance/src/server_config/queries.rs
  agent_issuance/src/startup_commands.rs
  agent_secret_manager/Cargo.toml
  agent_shared/src/config.rs
  agent_shared/tests/.env.test
  agent_verification/src/services.rs
Labels: Breaking change

#84 fix: move .dockerignore to the root, because it won't be respected otherwise
  .dockerignore
Labels: Chore

#88 chore: revert api version to `v0`
  .env.example
  CHANGELOG.md
  README.md
  agent_api_rest/README.md
  agent_api_rest/openapi.yaml
  agent_api_rest/postman/ssi-agent.postman_collection.json
  agent_api_rest/src/configurations/credential_configurations.rs
  agent_api_rest/src/issuance/credential_issuer/credential.rs
  agent_api_rest/src/issuance/credentials.rs
  agent_api_rest/src/issuance/offers.rs
  agent_api_rest/src/lib.rs
  agent_api_rest/src/verification/authorization_requests.rs
  agent_application/docker/README.md
  agent_application/docker/docker-compose.yml
  agent_application/src/main.rs
Labels: Breaking change

#91 feat: add `issuance-config.yml` file, deprecate `/v0/configurations/credential_configurations` endpoint
  Cargo.lock
  agent_api_rest/Cargo.toml
  agent_api_rest/README.md
  agent_api_rest/postman/ssi-agent.postman_collection.json
  agent_api_rest/src/configurations/credential_configurations.rs
  agent_api_rest/src/configurations/mod.rs
  agent_api_rest/src/issuance/credential_issuer/credential.rs
  agent_api_rest/src/issuance/credential_issuer/token.rs
  agent_api_rest/src/issuance/credential_issuer/well_known/openid_credential_issuer.rs
  agent_api_rest/src/issuance/credentials.rs
  agent_api_rest/src/issuance/offers.rs
  agent_api_rest/src/lib.rs
  agent_application/docker/Dockerfile
  agent_application/docker/docker-compose.yml
  agent_event_publisher_http/Cargo.toml
  agent_event_publisher_http/src/lib.rs
  agent_issuance/Cargo.toml
  agent_issuance/README.md
  agent_issuance/issuance-config.yml
  agent_issuance/src/credential/aggregate.rs
  agent_issuance/src/server_config/aggregate.rs
  agent_issuance/src/server_config/command.rs
  agent_issuance/src/startup_commands.rs
  agent_secret_manager/Cargo.toml
  agent_shared/Cargo.toml
  agent_shared/src/config.rs
  agent_shared/src/issuance.rs
  agent_shared/src/lib.rs
  agent_shared/src/metadata.rs
  agent_shared/tests/.env.test
  agent_shared/tests/config.rs
  agent_verification/Cargo.toml
  agent_verification/src/services.rs
Labels: Breaking change
