Repository impierce/ssi-agent, pull requests merged in 2025-03, with the labels that each got.

#168 feat: remove ˋdid:iota:rmsˋ DID method (discontinued)
  .env.example
  agent_api_rest/src/issuance/credential_issuer/well_known/openid_credential_issuer.rs
  agent_application/docker/compose.yaml
  agent_application/example.config.yaml
  agent_issuance/src/credential/aggregate.rs
  agent_secret_manager/src/lib.rs
  agent_secret_manager/src/subject.rs
  agent_shared/src/config.rs
  agent_shared/tests/test-config.yaml
  agent_verification/src/authorization_request/aggregate.rs
Labels: BREAKING CHANGE, Removed

#166 feat: use `credential_offer_uri` by default during credential issuance
  Cargo.lock
  agent_api_rest/postman/ssi-agent.postman_collection.json
  agent_api_rest/src/issuance/credential_issuer/credential.rs
  agent_api_rest/src/issuance/credential_issuer/token.rs
  agent_api_rest/src/issuance/mod.rs
  agent_api_rest/src/issuance/offers/mod.rs
  agent_issuance/src/offer/aggregate.rs
  agent_issuance/src/offer/command.rs
  agent_issuance/src/offer/error.rs
  agent_issuance/src/offer/event.rs
  agent_issuance/src/offer/views/mod.rs
  agent_shared/src/config.rs
  agent_shared/tests/test-config.yaml
Labels: Added, Enhancement

#160 feat: add Domain Linkage for `did:iota` DID Method
  .env.example
  Cargo.lock
  Cargo.toml
  agent_api_rest/Cargo.toml
  agent_api_rest/src/identity/services/linked_vp.rs
  agent_api_rest/src/identity/well_known/did.rs
  agent_api_rest/src/identity/well_known/did_configuration.rs
  agent_api_rest/src/verification/relying_party/redirect.rs
  agent_application/CONFIGURATION.md
  agent_application/docker/README.md
  agent_application/docker/compose.yaml
  agent_application/docker/db/init.sql
  agent_application/example.config.yaml
  agent_application/src/main.rs
  agent_event_publisher_http/README.md
  agent_holder/Cargo.toml
  agent_holder/src/credential/aggregate.rs
  agent_holder/src/offer/aggregate.rs
  agent_holder/src/presentation/aggregate.rs
  agent_identity/Cargo.toml
  agent_identity/src/connection/aggregate.rs
  agent_identity/src/document/aggregate.rs
  agent_identity/src/document/command.rs
  agent_identity/src/document/error.rs
  agent_identity/src/document/event.rs
  agent_identity/src/document/views/all_documents.rs
  agent_identity/src/document/views/mod.rs
  agent_identity/src/service/aggregate.rs
  agent_identity/src/service/command.rs
  agent_identity/src/service/error.rs
  agent_identity/src/service/event.rs
  agent_identity/src/service/views/mod.rs
  agent_identity/src/services.rs
  agent_identity/src/state.rs
  agent_issuance/Cargo.toml
  agent_issuance/src/credential/aggregate.rs
  agent_issuance/src/offer/aggregate.rs
  agent_issuance/src/offer/error.rs
  agent_issuance/src/server_config/aggregate.rs
  agent_issuance/src/state.rs
  agent_secret_manager/Cargo.toml
  agent_secret_manager/src/lib.rs
  agent_secret_manager/src/service.rs
  agent_secret_manager/src/subject.rs
  agent_secret_manager/tests/res/selv.stronghold
  agent_secret_manager/tests/res/test.stronghold.dat
  agent_shared/src/config.rs
  agent_shared/src/handlers.rs
  agent_shared/tests/test-config.yaml
  agent_store/src/in_memory.rs
  agent_store/src/postgres.rs
  agent_verification/Cargo.toml
  agent_verification/src/authorization_request/aggregate.rs
  docs/deployment/domain-linkage.md
  docs/introduction/quick-start.md
Labels: Added, BREAKING CHANGE

#171 feat: add endpoints to list and retrieve DID Documents
  agent_api_rest/postman/ssi-agent.postman_collection.json
  agent_api_rest/src/identity/connections/mod.rs
  agent_api_rest/src/identity/documents/mod.rs
  agent_api_rest/src/identity/mod.rs
Labels: Added, Blocked

#158 feat: add `/version` and `/info` metadata endpoints
  .github/workflows/build-push-docker.yaml
  Cargo.lock
  agent_api_rest/postman/ssi-agent.postman_collection.json
  agent_application/Cargo.toml
  agent_application/build.rs
  agent_application/docker/Dockerfile
  agent_application/src/main.rs
  agent_application/src/metadata/info.rs
  agent_application/src/metadata/mod.rs
  agent_application/src/metadata/version.rs
  docs/deployment/monitoring.md
Labels: Added

#175 feat: add Problem Details for Issuance and Persistence HTTP API errors
  Cargo.lock
  Cargo.toml
  agent_api_rest/Cargo.toml
  agent_api_rest/src/error.rs
  agent_api_rest/src/handlers.rs
  agent_api_rest/src/holder/error.rs
  agent_api_rest/src/holder/holder/credentials/mod.rs
  agent_api_rest/src/holder/holder/offers/accept.rs
  agent_api_rest/src/holder/holder/offers/mod.rs
  agent_api_rest/src/holder/holder/offers/reject.rs
  agent_api_rest/src/holder/holder/presentations/mod.rs
  agent_api_rest/src/holder/holder/presentations/presentation_signed.rs
  agent_api_rest/src/holder/mod.rs
  agent_api_rest/src/holder/openid4vci/mod.rs
  agent_api_rest/src/identity/connections/mod.rs
  agent_api_rest/src/identity/documents/mod.rs
  agent_api_rest/src/identity/error.rs
  agent_api_rest/src/identity/mod.rs
  agent_api_rest/src/identity/services/linked_vp.rs
  agent_api_rest/src/identity/services/mod.rs
  agent_api_rest/src/identity/well_known/did.rs
  agent_api_rest/src/identity/well_known/did_configuration.rs
  agent_api_rest/src/issuance/credential_issuer/credential.rs
  agent_api_rest/src/issuance/credential_issuer/credential_offer.rs
  agent_api_rest/src/issuance/credential_issuer/mod.rs
  agent_api_rest/src/issuance/credential_issuer/token.rs
  agent_api_rest/src/issuance/credential_issuer/well_known/oauth_authorization_server.rs
  agent_api_rest/src/issuance/credential_issuer/well_known/openid_credential_issuer.rs
  agent_api_rest/src/issuance/credentials.rs
  agent_api_rest/src/issuance/error.rs
  agent_api_rest/src/issuance/mod.rs
  agent_api_rest/src/issuance/offers/mod.rs
  agent_api_rest/src/issuance/offers/send.rs
  agent_api_rest/src/lib.rs
  agent_api_rest/src/verification/authorization_requests.rs
  agent_api_rest/src/verification/error.rs
  agent_api_rest/src/verification/mod.rs
  agent_api_rest/src/verification/relying_party/redirect.rs
  agent_api_rest/src/verification/relying_party/request.rs
  agent_holder/src/offer/aggregate.rs
  agent_issuance/Cargo.toml
  agent_issuance/src/credential/aggregate.rs
  agent_issuance/src/credential/error.rs
  agent_issuance/src/offer/aggregate.rs
  agent_issuance/src/offer/error.rs
  agent_issuance/src/offer/views/mod.rs
  agent_verification/src/authorization_request/aggregate.rs
  agent_verification/src/authorization_request/error.rs
  docs/problem-details/issuance.md
  docs/problem-details/persistence.md
  docs/problem-details/unexpected.md
Labels: Added
